package:
    name: inchipy
    version: 0.1.0

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
    run:
        - python
        - pytest
