version: 2
jobs:
    build-ubuntu:
        docker:
            - image: circleci/python:3.7
        steps:
          - checkout
          - run:
              name: Build and install
              command: |
                  git submodule init
                  git submodule update
                  sudo pip install pytest
                  sudo apt-get install gcc cmake
                  cmake . -DCMAKE_INSTALL_PREFIX=/usr
                  sudo make install
          - run:
              name: Run examples
              command: |
                  pytest -v tests/
workflows:
    version: 2
    build-all:
        jobs:
            - build-ubuntu
